#include "ShaderWater.h"

bool ShaderWater::CreateShader()
{
    std::string vert = std::string(shaderHeader) +
        "layout(location = 0) in vec3 aPos;\n"
        "layout(location = 1) in vec3 aNormal;\n"
        "layout(location = 2) in vec2 aTexCoord;\n"
        "out VS_OUT {\n"
        "    vec3 pos;\n"
        "    vec3 normal;\n"
        "    vec2 texCoord;\n"
        "} vs_out;\n"
        "void main() {\n"
        "    vs_out.pos = aPos;\n"
        "    vs_out.normal = aNormal;\n"
        "    vs_out.texCoord = aTexCoord;\n"
        "}\n";

    std::string geom = std::string(shaderHeader) +
        "layout(triangles) in;\n"
        "layout(triangle_strip, max_vertices = 12) out;\n"
        "in VS_OUT {\n"
        "    vec3 pos;\n"
        "    vec3 normal;\n"
        "    vec2 texCoord;\n"
        "} gs_in[];\n"
        "out vec3 FragPos;\n"
        "out vec3 Normal;\n"
        "out vec2 TexCoord;\n"
        "out float v_Height;\n"
        "uniform mat4 model;\n"
        "uniform float u_Time;\n"
        "uniform float waveSpeed;\n"
        "uniform float waveAmplitude;\n"
        "uniform float waveFrequency;\n"
        "struct Wave { vec2 direction; float steepness; float wavelength; };\n"
        "vec3 GerstnerWave(vec3 p, Wave w, float time, inout vec3 tangent, inout vec3 binormal) {\n"
        "    float k = 2.0 * 3.14159 / w.wavelength;\n"
        "    float c = sqrt(9.8 / k);\n"
        "    vec2 d = normalize(w.direction);\n"
        "    float f = k * (dot(d, p.xz) - c * time * waveSpeed);\n"
        "    float a = (w.steepness / k) * waveAmplitude;\n"
        "    float overlapCheck = w.steepness * waveAmplitude;\n"
        "    float hScale = (overlapCheck > 0.35) ? 0.35 / overlapCheck : 1.0;\n"
        "    float cosf = cos(f); float sinf = sin(f);\n"
        "    vec3 disp = vec3(d.x*(a*hScale*cosf), a*sinf, d.y*(a*hScale*cosf));\n"
        "    float wa = k*a; float wa_h = wa*hScale;\n"
        "    tangent  += vec3(-d.x*d.x*(wa_h*sinf), d.x*(wa*cosf), -d.x*d.y*(wa_h*sinf));\n"
        "    binormal += vec3(-d.x*d.y*(wa_h*sinf), d.y*(wa*cosf), -d.y*d.y*(wa_h*sinf));\n"
        "    return disp;\n"
        "}\n"
        "vec3 ApplyWaves(vec3 p, out vec3 normal, out float height) {\n"
        "    vec3 fp = p; vec3 t = vec3(1,0,0); vec3 b = vec3(0,0,1);\n"
        "    Wave w1 = Wave(vec2(1.0,0.5),  0.15, 6.0/waveFrequency);\n"
        "    Wave w2 = Wave(vec2(0.6,1.0),  0.10, 3.5/waveFrequency);\n"
        "    Wave w3 = Wave(vec2(-0.4,0.8), 0.10, 2.0/waveFrequency);\n"
        "    fp += GerstnerWave(p,w1,u_Time,t,b);\n"
        "    fp += GerstnerWave(p,w2,u_Time,t,b);\n"
        "    fp += GerstnerWave(p,w3,u_Time,t,b);\n"
        "    normal = normalize(cross(b,t)); height = fp.y;\n"
        "    return fp;\n"
        "}\n"
        "void EmitV(vec3 pos, vec2 tex) {\n"
        "    vec3 n; float h;\n"
        "    vec3 wp = ApplyWaves(pos, n, h);\n"
        "    v_Height = h;\n"
        "    FragPos = vec3(model * vec4(wp, 1.0));\n"
        "    Normal = normalize(mat3(transpose(inverse(model))) * n);\n"
        "    TexCoord = tex;\n"
        "    gl_Position = projection * view * vec4(FragPos, 1.0);\n"
        "    EmitVertex();\n"
        "}\n"
        "void main() {\n"
        "    vec3 v0=gs_in[0].pos, v1=gs_in[1].pos, v2=gs_in[2].pos;\n"
        "    vec3 m1=(v0+v1)/2.0, m2=(v1+v2)/2.0, m3=(v2+v0)/2.0;\n"
        "    vec2 t0=gs_in[0].texCoord, t1=gs_in[1].texCoord, t2=gs_in[2].texCoord;\n"
        "    vec2 tm1=(t0+t1)/2.0, tm2=(t1+t2)/2.0, tm3=(t2+t0)/2.0;\n"
        "    EmitV(v0,t0);   EmitV(m1,tm1); EmitV(m3,tm3); EndPrimitive();\n"
        "    EmitV(m3,tm3);  EmitV(m2,tm2); EmitV(v2,t2);  EndPrimitive();\n"
        "    EmitV(m1,tm1);  EmitV(v1,t1);  EmitV(m2,tm2); EndPrimitive();\n"
        "    EmitV(m1,tm1);  EmitV(m2,tm2); EmitV(m3,tm3); EndPrimitive();\n"
        "}\n";

    std::string frag =
        "#version 460 core\n"
        "out vec4 FragColor;\n"
        "in vec3 FragPos;\n"
        "in vec3 Normal;\n"
        "in vec2 TexCoord;\n"
        "in float v_Height;\n"
        "uniform vec3 lightDir;\n"
        "uniform vec3 viewPos;\n"
        "uniform float waveAmplitude;\n"
        "uniform float opacity;\n"
        "void main() {\n"
        "    vec3 viewDir = normalize(viewPos - FragPos);\n"
        "    vec3 norm = normalize(Normal);\n"
        "    vec3 light = normalize(-lightDir);\n"
        "    vec3 halfway = normalize(light + viewDir);\n"
        "    vec3 deep    = vec3(0.0, 0.1, 0.4);\n"
        "    vec3 shallow = vec3(0.0, 0.4, 0.6);\n"
        "    vec3 foam    = vec3(1.0, 1.0, 1.0);\n"
        "    float hf = smoothstep(-0.5*waveAmplitude, 0.8*waveAmplitude, v_Height);\n"
        "    vec3 albedo = mix(deep, shallow, hf);\n"
        "    float ff = smoothstep(0.4*waveAmplitude, 0.6*waveAmplitude, v_Height);\n"
        "    albedo = mix(albedo, foam, ff);\n"
        "    vec3 ambient = 0.1 * albedo;\n"
        "    float diff = max(dot(norm, light), 0.0);\n"
        "    float spec = pow(max(dot(norm, halfway), 0.0), 128.0);\n"
        "    float F0 = 0.02;\n"
        "    float fresnel = F0 + (1.0-F0) * pow(1.0 - max(dot(norm,viewDir),0.0), 5.0);\n"
        "    vec3 result = ambient + diff*albedo + vec3(0.8)*spec;\n"
        "    float alpha = mix(0.7, 0.95, fresnel);\n"
        "    FragColor = vec4(result, alpha * opacity);\n"
        "}\n";

    return LoadFromSource(vert.c_str(), frag.c_str(), geom.c_str());
}