#include "ShaderStandard.h"

bool ShaderStandard::CreateShader()
{
    std::string vert = std::string(shaderHeader) + skinningDeclarations + skinningFunction +
        "layout(location = 0) in vec3 aPos;\n"
        "layout(location = 1) in vec3 aNormal;\n"
        "layout(location = 2) in vec2 aTexCoord;\n"
        "layout(location = 3) in ivec4 boneIDs;\n"
        "layout(location = 4) in vec4 weights;\n"
        "layout(location = 5) in vec3 aTangent;\n"
        "\n"
        "out VS_OUT {\n"
        "    vec3 FragPos;\n"
        "    vec2 TexCoord;\n"
        "    vec3 Normal;\n"
        "    mat3 TBN;\n"
        "    vec3 TangentViewPos;\n"
        "    vec3 TangentFragPos;\n"
        "} vs_out;\n"
        "\n"
        "uniform vec3 viewPos;\n"
        "\n"
        "void main() {\n"
        "    mat4 skinMat = GetSkinMatrix(boneIDs, weights);\n"
        "    vec4 worldPos = model * skinMat * vec4(aPos, 1.0);\n"
        "    vs_out.FragPos = worldPos.xyz;\n"
        "    vs_out.TexCoord = aTexCoord;\n"
        "    \n"
        "    mat3 normalMatrix = transpose(inverse(mat3(model * skinMat)));\n"
        "    vec3 T = normalize(normalMatrix * aTangent);\n"
        "    vec3 N = normalize(normalMatrix * aNormal);\n"
        "    T = normalize(T - dot(T, N) * N);\n"
        "    vec3 B = cross(N, T);\n"
        "    mat3 TBN = transpose(mat3(T, B, N));\n"
        "    \n"
        "    vs_out.TBN = TBN;\n"
        "    vs_out.TangentViewPos = TBN * viewPos;\n"
        "    vs_out.TangentFragPos = TBN * worldPos.xyz;\n"
        "    vs_out.Normal = N;\n"
        "    \n"
        "    gl_Position = projection * view * worldPos;\n"
        "}\n";

    std::string frag =
        "#version 460 core\n"
        "out vec4 FragColor;\n"
        "in VS_OUT {\n"
        "    vec3 FragPos;\n"
        "    vec2 TexCoord;\n"
        "    vec3 Normal;\n"
        "    mat3 TBN;\n"
        "    vec3 TangentViewPos;\n"
        "    vec3 TangentFragPos;\n"
        "} fs_in;\n"
        "\n"
        "uniform sampler2D uAlbedoMap;\n"
        "uniform sampler2D uNormalMap;\n"
        "uniform sampler2D uMetallicMap;\n"
        "uniform sampler2D uOcclusionMap;\n"
        "uniform sampler2D uHeightMap;\n"
        "\n"
        "uniform vec4 uColor;\n"
        "uniform float uMetallic;\n"
        "uniform float uRoughness;\n"
        "uniform float uHeightScale;\n"
        "uniform vec2 uTiling;\n"
        "uniform vec2 uOffset;\n"
        "\n"
        "vec2 ParallaxMapping(vec2 texCoords, vec3 viewDir) {\n"
        "    float height = texture(uHeightMap, texCoords).r;\n"
        "    return texCoords - viewDir.xy * (height * uHeightScale);\n"
        "}\n"
        "\n"
        "void main() {\n"
        "    vec3 viewDir = normalize(fs_in.TangentViewPos - fs_in.TangentFragPos);\n"
        "    vec2 uv = fs_in.TexCoord * uTiling + uOffset;\n"
        "    \n"
        "    // Aplicar relieve si hay textura de altura\n"
        "    if (uHeightScale > 0.0) uv = ParallaxMapping(uv, viewDir);\n"
        "    if(uv.x > 1.0 || uv.y > 1.0 || uv.x < 0.0 || uv.y < 0.0) discard;\n"
        "\n"
        "    vec4 albedo = texture(uAlbedoMap, uv) * uColor;\n"
        "    if (albedo.a < 0.1) discard;\n"
        "\n"
        "    // Normal mapping\n"
        "    vec3 normal = texture(uNormalMap, uv).rgb;\n"
        "    normal = normalize(normal * 2.0 - 1.0);\n"
        "    normal = normalize(fs_in.TBN * normal);\n"
        "\n"
        "    // Iluminación muy simplificada (Ambiente + Difusa)\n"
        "    vec3 lightDir = normalize(vec3(0.5, 1.0, 0.3));\n"
        "    float diff = max(dot(normal, lightDir), 0.2);\n"
        "    \n"
        "    FragColor = vec4(albedo.rgb * diff, albedo.a);\n"
        "}\n";

    return LoadFromSource(vert.c_str(), frag.c_str());
}